# -*- coding: utf-8 -*-
"""Demo_TFM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qtBpi3u7f8M5zrijN5DhaUZIB-KCIZC

# ChiGNN — DEMO INTERACTIVA PARA LA DEFENSA DEL TFM

Este script permite cargar cualquier archivo PDB, eliminar
 sus cadenas laterales (quedándose solo con el backbone) y
 recuperarlas usando el modelo ChiGNN entrenado.

 CÓMO USARLO EN GOOGLE COLAB:
   1. Abre este archivo en Colab o pégalo en un notebook nuevo.
   2. Asegúrate de tener GPU activa (T4 recomendado).
   3. Monta tu Google Drive (el checkpoint está ahí).
   4. Ejecuta las celdas en orden.
   5. Cuando se pida, sube tu archivo .pdb.

 REQUISITO: el checkpoint entrenado debe estar en Drive en:
   MyDrive/TFM_SideChain/chignn_best.pt
"""

# ── Celda 1: Instalación de dependencias ─────────────────────
# (Ignorar warnings de compatibilidad — son inofensivos)
import subprocess, sys

def pip_install(pkg):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg])

pip_install("biopython")
pip_install("py3Dmol")

import torch
torch_version = torch.__version__.split('+')[0]
cuda_version  = torch.version.cuda.replace('.', '') if torch.version.cuda else "cpu"

if torch.cuda.is_available():
    subprocess.run([
        sys.executable, "-m", "pip", "install", "-q", "torch-scatter",
        "-f", f"https://data.pyg.org/whl/torch-{torch_version}+cu{cuda_version}.html"
    ])
    subprocess.run([
        sys.executable, "-m", "pip", "install", "-q", "torch-sparse",
        "-f", f"https://data.pyg.org/whl/torch-{torch_version}+cu{cuda_version}.html"
    ])

pip_install("torch-geometric")

print("✅ Dependencias instaladas correctamente.")

# ── Celda 2: Importaciones ────────────────────────────────────
import os
import numpy as np
import torch
import torch.nn as nn
import Bio.PDB
import py3Dmol
import warnings

warnings.filterwarnings("ignore")  # Silencia warnings de Biopython sobre estructuras

from torch_geometric.data  import Data
from torch_geometric.nn    import GCNConv
from torch_geometric.loader import DataLoader

print(f"🔧 Dispositivo: {'GPU — ' + torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

# ── Celda 3: Montar Google Drive ──────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# Ruta al checkpoint entrenado (misma que en el notebook principal)
DRIVE_BASE    = "/content/drive/MyDrive/TFM_SideChain"
CHECKPOINT_PT = f"{DRIVE_BASE}/chignn_best.pt"

if not os.path.exists(CHECKPOINT_PT):
    raise FileNotFoundError(
        f"❌ No se encontró el checkpoint en: {CHECKPOINT_PT}\n"
        "   Asegúrate de que el archivo chignn_best.pt está en Drive."
    )

print(f"✅ Checkpoint encontrado: {CHECKPOINT_PT}")

# ── Celda 4: Constantes del modelo ───────────────────────────
# Deben coincidir EXACTAMENTE con los valores usados en el entrenamiento.
# Cambiar estos valores sin re-entrenar produciría predicciones incorrectas.

T         = 100      # Pasos totales de difusión
KAPPA_MAX = 10.0     # Concentración máxima de Von Mises (t=0, sin ruido)
KAPPA_MIN = 0.01     # Concentración mínima de Von Mises (t=T, ruido total)

# Mapeo de aminoácidos a índice entero (idéntico al notebook de entrenamiento)
AA_TO_IDX = {
    'ALA': 0,  'ARG': 1,  'ASN': 2,  'ASP': 3,  'CYS': 4,
    'GLN': 5,  'GLU': 6,  'GLY': 7,  'HIS': 8,  'ILE': 9,
    'LEU': 10, 'LYS': 11, 'MET': 12, 'PHE': 13, 'PRO': 14,
    'SER': 15, 'THR': 16, 'TRP': 17, 'TYR': 18, 'VAL': 19
}

def get_kappa(t: int) -> float:
    """
    Devuelve la concentración κ en el paso t.
    Schedule lineal: t=0 → κ_max (sin ruido), t=T → κ_min (ruido total).
    """
    return KAPPA_MAX - (KAPPA_MAX - KAPPA_MIN) * (t / T)

def von_mises_sample(mu: torch.Tensor, kappa: float) -> torch.Tensor:
    """
    Muestrea ángulos de Von Mises VM(μ, κ) usando NumPy.
    Devuelve tensor en [-π, π].
    """
    samples_np = np.random.vonmises(mu.cpu().numpy(), kappa)
    return torch.tensor(samples_np, dtype=torch.float)

# ── Celda 5: Arquitectura ChiGNN ─────────────────────────────
# Definición IDÉNTICA a la del notebook de entrenamiento.
# Cualquier diferencia (hidden_dim, n_layers, aa_embed) haría
# incompatible la carga de pesos del checkpoint.

class ChiGNN(nn.Module):
    """
    Red Neuronal de Grafos para denoising de ángulos chi.
    Versión 'lite' inspirada en DiffPack, diseñada para Google Colab T4.

    Entrada por nodo: coordenadas backbone (9) + embedding aminoácido (16)
                    + sin/cos de χ_t (8) + paso de tiempo t (1) = 34 features
    Salida por nodo: 4 ángulos chi predichos en [-π, π]
    """

    def __init__(self, hidden_dim=128, n_layers=4, aa_embed=16):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.n_layers   = n_layers
        self.aa_embedding = nn.Embedding(21, aa_embed)

        input_dim = 9 + aa_embed + 8 + 1   # backbone + aa + chi_enc + t

        self.input_proj = nn.Sequential(nn.Linear(input_dim, hidden_dim), nn.SiLU())

        self.conv_layers = nn.ModuleList([GCNConv(hidden_dim, hidden_dim) for _ in range(n_layers)])
        self.norms       = nn.ModuleList([nn.BatchNorm1d(hidden_dim)       for _ in range(n_layers)])
        self.acts        = nn.ModuleList([nn.SiLU()                        for _ in range(n_layers)])

        self.output_head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2), nn.SiLU(),
            nn.Linear(hidden_dim // 2, 4)
        )

    def encode_angles(self, chi):
        """Codifica ángulos como pares (sin, cos) para respetar periodicidad."""
        return torch.cat([torch.sin(chi), torch.cos(chi)], dim=-1)

    def forward(self, x, aa_type, edge_index, chi_noisy, t_node):
        aa_emb    = self.aa_embedding(aa_type)
        chi_enc   = self.encode_angles(chi_noisy)
        node_feat = torch.cat([x, aa_emb, chi_enc, t_node], dim=-1)
        h         = self.input_proj(node_feat)

        for conv, norm, act in zip(self.conv_layers, self.norms, self.acts):
            h = h + act(norm(conv(h, edge_index)))   # Conexión residual

        return torch.tanh(self.output_head(h)) * torch.pi   # Salida en [-π, π]

# ── Celda 6: Cargar el modelo entrenado ──────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = ChiGNN(hidden_dim=128, n_layers=4, aa_embed=16).to(device)

ckpt = torch.load(CHECKPOINT_PT, map_location=device, weights_only=False)
model.load_state_dict(ckpt['model_state_dict'])
model.eval()   # Modo inferencia: desactiva dropout y usa estadísticas fijas de BatchNorm

epoca_guardada = ckpt.get('epoch', '?')
val_loss_ckpt  = ckpt.get('val_loss', '?')

print(f"✅ Modelo ChiGNN cargado correctamente.")
print(f"   Checkpoint: época {epoca_guardada} | val_loss = {val_loss_ckpt:.4f}")
print(f"   Parámetros: {sum(p.numel() for p in model.parameters()):,}")

"""Para probar el modelo, hay que tener previamente descargado el archivo tipo ".pdb" de la proteína que deseamos probar.

Para ello es necesario seguir los siguientes pasos:

1.   Entrar en https://rcsb.org/
2.   Buscar la proteína que queremos probar por su códigp de 4 letras
3.   Descargar -> Formato PDB

Cuando la Celda 7 requiera "Selecciona un archivo .pdb para predecir sus cadenas laterales" deberemos seleccionar el archivo ".pdb" descargado de nuestra proteína.

Usaremos proteínas que no hayan sido objeto de entrenamiento del modelo y a poder ser, que su relosución sea inferior a 2,0 Å para aplicar el mismo criterio de calidad que en el entrenamiento.




"""

# ── Celda 7: Subir el archivo PDB ────────────────────────────
from google.colab import files

print("📂 Selecciona un archivo .pdb para predecir sus cadenas laterales:")
uploaded = files.upload()

pdb_path = list(uploaded.keys())[0]
pdb_name = os.path.splitext(pdb_path)[0].upper()
print(f"✅ Archivo recibido: {pdb_path}")

# ── Celda 8: Parsear el PDB y construir el grafo ─────────────
def pdb_to_graph(pdb_path: str) -> Data:
    """
    Lee un archivo PDB y construye el grafo de PyTorch Geometric
    que ChiGNN espera como input.

    Solo se usan las coordenadas del backbone (N, Cα, C).
    Las cadenas laterales se ignoran completamente — el modelo
    las predecirá desde cero.

    Parámetros
    ----------
    pdb_path : str — ruta al archivo .pdb

    Retorna
    -------
    torch_geometric.data.Data — grafo listo para inferencia
    """
    parser    = Bio.PDB.PDBParser(QUIET=True)
    structure = parser.get_structure("prot", pdb_path)

    coords_list = []   # Coordenadas backbone por residuo
    aa_list     = []   # Tipo de aminoácido por residuo
    skipped     = 0    # Residuos descartados (sin backbone completo)

    for model_pdb in structure:
        for chain in model_pdb:
            residues = sorted(chain.get_residues(), key=lambda r: r.get_id()[1])
            for residue in residues:
                res_name = residue.get_resname().strip()

                # Ignorar heteroátomos (agua, ligandos, etc.)
                if residue.get_id()[0] != ' ':
                    continue

                # Verificar que el backbone está completo
                atom_names = {a.get_name() for a in residue}
                if not {'N', 'CA', 'C'}.issubset(atom_names):
                    skipped += 1
                    continue

                # Extraer coordenadas de los tres átomos del backbone
                n_vec  = residue['N'].get_vector().get_array()
                ca_vec = residue['CA'].get_vector().get_array()
                c_vec  = residue['C'].get_vector().get_array()

                # El vector de features del nodo: [N_x, N_y, N_z, CA_x, ..., C_z]
                coords_list.append(np.concatenate([n_vec, ca_vec, c_vec]))
                aa_list.append(AA_TO_IDX.get(res_name, 20))   # 20 = desconocido

        break  # Solo usamos el primer modelo del PDB (por si hay NMR ensembles)

    if len(coords_list) == 0:
        raise ValueError("❌ No se encontraron residuos válidos en el PDB.")

    n_res = len(coords_list)

    # Construir aristas: grafo lineal bidireccional (cada residuo conectado
    # al anterior y al siguiente), replicando la topología del entrenamiento.
    src = list(range(n_res - 1)) + list(range(1, n_res))
    dst = list(range(1, n_res)) + list(range(n_res - 1))

    x          = torch.tensor(np.array(coords_list), dtype=torch.float)
    aa_type    = torch.tensor(aa_list, dtype=torch.long)
    edge_index = torch.tensor([src, dst], dtype=torch.long)

    # y e y_mask vacíos: el modelo predecirá los ángulos, no los conocemos
    y      = torch.zeros(n_res, 4, dtype=torch.float)
    y_mask = torch.zeros(n_res, 4, dtype=torch.bool)

    print(f"✅ Grafo construido:")
    print(f"   Residuos procesados : {n_res}")
    print(f"   Residuos omitidos   : {skipped} (backbone incompleto)")
    print(f"   Aristas (grafo)     : {edge_index.shape[1]}")

    return Data(x=x, aa_type=aa_type, edge_index=edge_index,
                y=y, y_mask=y_mask)

graph = pdb_to_graph(pdb_path)

# ── Celda 9: Proceso reverse — predicción de cadenas laterales
@torch.no_grad()
def predict_side_chains(model, graph, device, n_steps=20):
    """
    Aplica el proceso reverse de difusión torsional para predecir
    los ángulos chi de las cadenas laterales.

    Parte de ángulos aleatorios uniformes (ruido total, t=T) y
    aplica n_steps pasos de denoising usando ChiGNN para recuperar
    los ángulos originales χ_0.

    Parámetros
    ----------
    model   : ChiGNN entrenado
    graph   : Data — grafo de la proteína
    device  : torch.device
    n_steps : int — pasos de denoising (20 es suficiente para la demo)

    Retorna
    -------
    torch.Tensor [N_residuos, 4] — ángulos chi predichos en radianes
    """
    model.eval()
    graph = graph.to(device)
    N     = graph.num_nodes

    # Inicializar con ruido puro: ángulos uniformes en [-π, π]
    # Esto simula t=T, el punto de partida del proceso reverse.
    chi_t = torch.tensor(
        np.random.uniform(-np.pi, np.pi, size=(N, 4)),
        dtype=torch.float, device=device
    )

    # Pasos de tiempo decrecientes: T → 1
    timesteps = torch.linspace(T, 1, n_steps).long()

    for i, t_int in enumerate(timesteps):
        t_val  = t_int.item()
        t_norm = torch.full((N, 1), t_val / T, dtype=torch.float, device=device)

        # ChiGNN predice χ_0 a partir de los ángulos ruidosos χ_t
        chi_0_pred = model(
            x          = graph.x,
            aa_type    = graph.aa_type,
            edge_index = graph.edge_index,
            chi_noisy  = chi_t,
            t_node     = t_norm
        )

        # Excepto en el último paso, re-añadimos ruido de nivel t-1
        # (simulación de la cadena de Markov inversa, algoritmo DDIM)
        if t_val > 1:
            t_prev     = t_val - (T / n_steps)
            kappa_prev = get_kappa(int(t_prev))
            mask_all   = torch.ones(N, 4, dtype=torch.bool)
            chi_t      = von_mises_sample(
                torch.rad2deg(chi_0_pred).cpu(), kappa_prev
            ).to(device)
            # Convertir de vuelta a radianes para la siguiente iteración
            chi_t      = torch.deg2rad(chi_t)
        else:
            chi_t = chi_0_pred

    return chi_t.cpu()   # [N, 4] en radianes

print("🔄 Ejecutando proceso reverse (predicción de cadenas laterales)...")
chi_pred = predict_side_chains(model, graph, device, n_steps=20)
chi_pred_deg = torch.rad2deg(chi_pred)

print(f"✅ Predicción completada.")
print(f"   Residuos con χ₁ predicho: {graph.num_nodes}")
print(f"   Rango χ₁: [{chi_pred_deg[:, 0].min():.1f}°, {chi_pred_deg[:, 0].max():.1f}°]")

# ── Celda 10: Visualización del resultado ────────────────────
def apply_chi1_to_pdb(pdb_path: str, chi_pred_deg: torch.Tensor) -> str:
    """
    Aplica los ángulos χ₁ predichos a la estructura y devuelve
    el PDB modificado como string para visualización con py3Dmol.

    Solo modifica χ₁ para mantener la visualización clara.
    La modificación geométrica rota el átomo Cγ alrededor del
    enlace Cα–Cβ para posicionarlo según el ángulo predicho.

    Parámetros
    ----------
    pdb_path     : str — ruta al PDB original
    chi_pred_deg : tensor [N, 4] — ángulos predichos en grados

    Retorna
    -------
    str — contenido del PDB modificado (para py3Dmol)
    """
    import io
    from Bio.PDB import PDBIO

    parser    = Bio.PDB.PDBParser(QUIET=True)
    structure = parser.get_structure("prot", pdb_path)

    residue_idx = 0
    for model_pdb in structure:
        for chain in model_pdb:
            for residue in sorted(chain.get_residues(), key=lambda r: r.get_id()[1]):
                if residue.get_id()[0] != ' ':
                    continue
                atom_names = {a.get_name() for a in residue}
                if not {'N', 'CA', 'C'}.issubset(atom_names):
                    continue
                if residue_idx >= chi_pred_deg.shape[0]:
                    break

                # Obtener el átomo Cγ (o equivalente) si existe
                gamma_names = ['CG', 'CG1', 'OG', 'SG', 'OG1']
                gamma_atom  = next(
                    (residue[a] for a in gamma_names if a in atom_names), None
                )

                if gamma_atom is not None and 'CB' in atom_names:
                    chi1_target = float(chi_pred_deg[residue_idx, 0])
                    ca_vec = residue['CA'].get_vector()
                    cb_vec = residue['CB'].get_vector()

                    # Calcular χ₁ actual
                    n_vec  = residue['N'].get_vector()
                    g_vec  = gamma_atom.get_vector()
                    chi1_current = Bio.PDB.calc_dihedral(n_vec, ca_vec, cb_vec, g_vec)
                    chi1_current_deg = np.degrees(chi1_current)

                    # Rotar el átomo Cγ la diferencia angular necesaria
                    delta = np.radians(chi1_target - chi1_current_deg)
                    axis  = (cb_vec - ca_vec).normalized()
                    rot   = Bio.PDB.rotaxis(delta, axis)
                    new_g_vec = (g_vec - cb_vec).left_multiply(rot) + cb_vec
                    gamma_atom.set_coord(new_g_vec.get_array())

                residue_idx += 1
        break

    # Serializar la estructura modificada a string PDB
    output = io.StringIO()
    io_obj = PDBIO()
    io_obj.set_structure(structure)
    io_obj.save(output)
    return output.getvalue()

# Generar PDB con cadenas laterales predichas
pdb_modified = apply_chi1_to_pdb(pdb_path, chi_pred_deg)

# Visualizar con py3Dmol: backbone original en verde, cadenas laterales predichas en azul
print("🔬 Generando visualización 3D...")

view = py3Dmol.view(width=800, height=500)

# Estructura original (backbone en verde)
with open(pdb_path) as f:
    pdb_original = f.read()
view.addModel(pdb_original, 'pdb')
view.setStyle({'model': 0}, {
    'cartoon': {'color': 'green', 'opacity': 0.6},
    'stick':   {'colorscheme': 'greenCarbon', 'radius': 0.1}
})

# Estructura con cadenas laterales predichas (en azul)
view.addModel(pdb_modified, 'pdb')
view.setStyle({'model': 1}, {
    'cartoon': {'color': 'blue', 'opacity': 0.4},
    'stick':   {'colorscheme': 'blueCarbon', 'radius': 0.15}
})

view.zoomTo()
view.show()

print("✅ Visualización lista.")
print("   🟢 Verde  : estructura original (backbone)")
print("   🔵 Azul   : cadenas laterales predichas por ChiGNN")

# ── Celda 11: Tabla resumen de predicciones ──────────────────
# Muestra los ángulos chi predichos por residuo en formato tabla,

import pandas as pd

# Número de ángulos chi válidos por tipo de aminoácido.
# Aminoácidos con 0 chi (ALA, GLY, PRO) no tienen cadena lateral
# rotable, por lo que todos sus valores predichos son descartados.
CHI_COUNT = {
    'ALA': 0, 'GLY': 0, 'PRO': 0,
    'SER': 1, 'CYS': 1, 'THR': 1, 'VAL': 1,
    'ILE': 2, 'LEU': 2, 'ASP': 2, 'ASN': 2,
    'HIS': 2, 'PHE': 2, 'TRP': 2, 'TYR': 2,
    'GLU': 3, 'GLN': 3, 'MET': 3,
    'LYS': 4, 'ARG': 4
}

# Reconstruir la lista de residuos con su nombre de tres letras
parser    = Bio.PDB.PDBParser(QUIET=True)
structure = parser.get_structure("prot", pdb_path)

residue_names = []   # "GLU A12"
residue_types = []   # "GLU" (para consultar CHI_COUNT)

for model_pdb in structure:
    for chain in model_pdb:
        for residue in sorted(chain.get_residues(), key=lambda r: r.get_id()[1]):
            if residue.get_id()[0] != ' ':
                continue
            atom_names = {a.get_name() for a in residue}
            if not {'N', 'CA', 'C'}.issubset(atom_names):
                continue
            chain_id = chain.get_id()
            res_id   = residue.get_id()[1]
            res_name = residue.get_resname().strip()
            residue_names.append(f"{res_name} {chain_id}{res_id}")
            residue_types.append(res_name)
    break

n_show = min(len(residue_names), chi_pred_deg.shape[0])

# Construir la tabla filtrando ángulos sin significado biológico
rows = []
for i in range(n_show):
    res_type  = residue_types[i]
    n_chi     = CHI_COUNT.get(res_type, 1)  # Si es desconocido, mostramos χ₁

    def fmt(chi_idx):
        """Devuelve el ángulo formateado o '—' si no corresponde al aminoácido."""
        if chi_idx < n_chi:
            return f"{chi_pred_deg[i, chi_idx].item():.1f}°"
        return "—"

    rows.append({
        'Residuo': residue_names[i],
        'χ₁':     fmt(0),
        'χ₂':     fmt(1),
        'χ₃':     fmt(2),
        'χ₄':     fmt(3),
    })

df = pd.DataFrame(rows)

print(f"\n📋 Ángulos chi predichos por ChiGNN — {pdb_name}")
print(f"   (mostrando {n_show} residuos · '—' = ángulo no definido para ese aminoácido)\n")
print(df.to_string(index=False))

# ── Celda 12: Extraer ángulos chi experimentales del PDB ─────
# El archivo PDB contiene las posiciones reales de todos los átomos,
# lo que permite calcular los ángulos chi de referencia con Biopython
# y compararlos directamente con las predicciones de ChiGNN.

def extract_chi_from_pdb(pdb_path: str):
    """
    Extrae los ángulos chi reales de un archivo PDB usando Biopython.
    Devuelve un tensor [N_residuos, 4] en grados, con NaN donde el
    ángulo no existe o no puede calcularse por falta de átomos.

    Los ángulos se calculan usando calc_dihedral() de Biopython,
    idéntico al procedimiento del pipeline de entrenamiento.
    """
    parser    = Bio.PDB.PDBParser(QUIET=True)
    structure = parser.get_structure("prot", pdb_path)

    # Definición de los átomos que forman cada ángulo chi por ángulo
    # (átomo delta = extremo del diedro en ese nivel)
    DELTA_ATOMS = {
        1: ['CG', 'CG1', 'OG', 'SG', 'OG1'],   # χ₁
        2: ['CD', 'CD1', 'ND1', 'OD1', 'SD'],   # χ₂
        3: ['CE', 'NE', 'OE1', 'NZ'],            # χ₃
        4: ['CZ', 'NH1', 'NZ'],                  # χ₄
    }

    chi_real = []

    for model_pdb in structure:
        for chain in model_pdb:
            for residue in sorted(chain.get_residues(), key=lambda r: r.get_id()[1]):
                if residue.get_id()[0] != ' ':
                    continue
                atom_names = {a.get_name() for a in residue}
                if not {'N', 'CA', 'C'}.issubset(atom_names):
                    continue

                angles = [np.nan, np.nan, np.nan, np.nan]

                if 'CB' in atom_names:
                    # χ₁: N – CA – CB – CG
                    gamma = next((residue[a] for a in DELTA_ATOMS[1] if a in atom_names), None)
                    if gamma:
                        angles[0] = np.degrees(Bio.PDB.calc_dihedral(
                            residue['N'].get_vector(),
                            residue['CA'].get_vector(),
                            residue['CB'].get_vector(),
                            gamma.get_vector()
                        ))

                    # χ₂: CA – CB – CG – CD
                    if gamma:
                        delta = next((residue[a] for a in DELTA_ATOMS[2] if a in atom_names), None)
                        if delta:
                            angles[1] = np.degrees(Bio.PDB.calc_dihedral(
                                residue['CA'].get_vector(),
                                residue['CB'].get_vector(),
                                gamma.get_vector(),
                                delta.get_vector()
                            ))

                            # χ₃: CB – CG – CD – CE
                            epsilon = next((residue[a] for a in DELTA_ATOMS[3] if a in atom_names), None)
                            if epsilon:
                                angles[2] = np.degrees(Bio.PDB.calc_dihedral(
                                    residue['CB'].get_vector(),
                                    gamma.get_vector(),
                                    delta.get_vector(),
                                    epsilon.get_vector()
                                ))

                                # χ₄: CG – CD – CE – CZ
                                zeta = next((residue[a] for a in DELTA_ATOMS[4] if a in atom_names), None)
                                if zeta:
                                    angles[3] = np.degrees(Bio.PDB.calc_dihedral(
                                        gamma.get_vector(),
                                        delta.get_vector(),
                                        epsilon.get_vector(),
                                        zeta.get_vector()
                                    ))

                chi_real.append(angles)
        break

    return np.array(chi_real, dtype=np.float32)   # [N, 4] en grados, con NaN

print("🔬 Extrayendo ángulos chi experimentales del PDB...")
chi_real = extract_chi_from_pdb(pdb_path)
chi_pred_np = chi_pred_deg.numpy()

print(f"✅ Ángulos experimentales extraídos: {chi_real.shape[0]} residuos")
print(f"   χ₁ con valor real: {np.sum(~np.isnan(chi_real[:, 0]))} residuos")
print(f"   χ₂ con valor real: {np.sum(~np.isnan(chi_real[:, 1]))} residuos")
print(f"   χ₃ con valor real: {np.sum(~np.isnan(chi_real[:, 2]))} residuos")
print(f"   χ₄ con valor real: {np.sum(~np.isnan(chi_real[:, 3]))} residuos")

# ── Celda 13: Métricas de evaluación ─────────────────────────
# Calcula las mismas métricas reportadas en el TFM (Capítulo 4)
# sobre la proteína de la demo:
#
#   · MAE circular:          error angular promedio respetando
#                             la periodicidad de los ángulos
#   · Recuperación ±20°:     % de predicciones con error < 20°
#   · Recuperación ±40°:     % de predicciones con error < 40°
#   · Estado rotamérico:     distribución predicha en g⁻ / t / g⁺
#
# NOTA: al ser una sola proteína, los valores pueden diferir
# de los del conjunto de test (597 proteínas). El resultado
# es orientativo y válido para ilustrar el funcionamiento
# del modelo durante la defensa.

def circular_mae(pred_deg: np.ndarray, real_deg: np.ndarray) -> float:
    """
    MAE circular en grados: mide la diferencia angular más corta
    entre predicción y valor real, ignorando la periodicidad.
    Equivalente a mean(min(|Δθ|, 360 - |Δθ|)).
    """
    diff = np.abs(pred_deg - real_deg) % 360
    diff = np.minimum(diff, 360 - diff)
    return float(np.mean(diff))

def recovery_rate(pred_deg: np.ndarray, real_deg: np.ndarray, tol: float) -> float:
    """
    Tasa de recuperación: % de predicciones con error circular < tol grados.
    """
    diff = np.abs(pred_deg - real_deg) % 360
    diff = np.minimum(diff, 360 - diff)
    return float(np.mean(diff < tol) * 100)

def rotamer_state(angle_deg: float) -> str:
    """
    Clasifica un ángulo χ₁ en su estado rotamérico canónico:
      g⁻ ≈ −60°  (gauche minus)
      t  ≈ 180°  (trans)
      g⁺ ≈ +60°  (gauche plus)
    """
    a = ((angle_deg + 180) % 360) - 180   # Normalizar a [-180, 180]
    if -120 <= a < 0:
        return "g⁻"
    elif a >= 120 or a < -120:
        return "t"
    else:
        return "g⁺"

n = min(chi_pred_np.shape[0], chi_real.shape[0])

print("=" * 55)
print(f"  📊 MÉTRICAS DE EVALUACIÓN — {pdb_name}")
print("=" * 55)

# ── MAE circular y recuperación por ángulo ────────────────────
print("\n🎯 Precisión angular (MAE circular y recuperación):\n")
print(f"  {'Ángulo':<8} {'MAE (°)':<12} {'Rec. ±20°':<14} {'Rec. ±40°':<14} {'N válidos'}")
print(f"  {'-'*60}")

for chi_idx, chi_name in enumerate(['χ₁', 'χ₂', 'χ₃', 'χ₄']):
    mask = ~np.isnan(chi_real[:n, chi_idx])
    if mask.sum() == 0:
        print(f"  {chi_name:<8} {'—':<12} {'—':<14} {'—':<14} 0")
        continue

    pred_valid = chi_pred_np[:n, chi_idx][mask]
    real_valid = chi_real[:n, chi_idx][mask]

    mae  = circular_mae(pred_valid, real_valid)
    r20  = recovery_rate(pred_valid, real_valid, 20)
    r40  = recovery_rate(pred_valid, real_valid, 40)
    n_v  = int(mask.sum())

    print(f"  {chi_name:<8} {mae:<12.1f} {r20:<14.1f} {r40:<14.1f} {n_v}")

# ── Referencia del TFM (conjunto de test completo) ────────────
print(f"\n  {'─'*60}")
print(f"  Referencia TFM (test set, 597 proteínas):")
print(f"  χ₁  MAE = 56,41°   Rec. ±40° = 53,9%")
print(f"  {'─'*60}")

# ── Distribución rotamérica de χ₁ predicha ───────────────────
mask_chi1 = ~np.isnan(chi_real[:n, 0])
if mask_chi1.sum() > 0:
    print(f"\n🔄 Distribución rotamérica de χ₁ predicha por ChiGNN:\n")

    pred_chi1 = chi_pred_np[:n, 0][mask_chi1]
    real_chi1 = chi_real[:n, 0][mask_chi1]
    n_valid   = len(pred_chi1)

    states_pred = [rotamer_state(a) for a in pred_chi1]
    states_real = [rotamer_state(a) for a in real_chi1]

    for state in ['g⁻', 't', 'g⁺']:
        n_pred = states_pred.count(state)
        n_real = states_real.count(state)
        pct_p  = n_pred / n_valid * 100
        pct_r  = n_real / n_valid * 100
        bar_p  = '█' * int(pct_p / 5)
        bar_r  = '░' * int(pct_r / 5)
        print(f"  {state}  predicho: {bar_p:<20} {pct_p:5.1f}%  ({n_pred} res.)")
        print(f"      real:      {bar_r:<20} {pct_r:5.1f}%  ({n_real} res.)\n")

# ── Tabla detallada pred vs real para χ₁ ─────────────────────
print(f"\n📋 Comparativa predicción vs. experimental (χ₁) — primeros 20 residuos con valor real:\n")

mask_chi1_full = ~np.isnan(chi_real[:n, 0])
idx_validos    = np.where(mask_chi1_full)[0][:20]

rows_cmp = []
for i in idx_validos:
    pred_a = chi_pred_np[i, 0]
    real_a = chi_real[i, 0]
    diff   = abs(pred_a - real_a) % 360
    diff   = min(diff, 360 - diff)
    ok_40  = "✅" if diff < 40 else "❌"
    rows_cmp.append({
        'Residuo':    residue_names[i] if i < len(residue_names) else str(i),
        'χ₁ pred (°)': f"{pred_a:.1f}",
        'χ₁ real (°)': f"{real_a:.1f}",
        'Error (°)':   f"{diff:.1f}",
        'Rotámero pred': rotamer_state(pred_a),
        'Rotámero real': rotamer_state(real_a),
        '±40°':        ok_40,
    })

df_cmp = pd.DataFrame(rows_cmp)
print(df_cmp.to_string(index=False))

print(f"\n{'='*55}")
print(f"  ✅ Evaluación completada sobre {pdb_name}")
print(f"{'='*55}")